Yalantis/Koloda

Pod/Classes/KolodaView/KolodaView.swift
none of KolodaViewDelegate functions are essential for KolodaView to work properly
they all must be optional but as @objc cannot be applied, i did this workaround
=> KolodaViewDelegate functions are practically optional

Pod/Classes/KolodaView/KolodaView.swift
By making `layoutDeck()` public, end users may trigger layout updates. For example, the layout can change sizes correctly when the device is rotated. This resolves #19 .
=> Makes method layoutDeck() public

Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift
Currently, when the user drags a card a short way and releases, the card animates back to the center. During this reset animation, the user cannot interact with the card. This can be frustrating to the user because the app feels (and, in fact, is) unresponsive during this time.
This pull request allows the card to be interacted with while it is resetting.
Due to issues with how the "center" is calculated, the center can shift if the card is rapidly dragged and re-dragged before it hits the center again. The DraggableCardView now stores its center only the very first time the card is dragged. There may be a more optimal approach.
=> Enable cards to be touched when they have finished dragging

Pod/Classes/KolodaView/KolodaView.swift
Fixes #50 by changing `setupDeck` to load cards based on `currentCardNumber`, rather than the current behavior (loading cards starting at 0). The main effect of this pull request is that if cards are dynamically added after the deck is exhausted, new cards will be shown, rather than card #0.
=> Fixes #50 by changing setupDeck to load cards based on currentCardNumber

Pod/Classes/KolodaView/KolodaView.swift
As a general rule of thumb, force unwraps should be avoided in nearly all cases. There might be some more crashes lurking in the codebase.
=> Fixed #61 by not force unwrapping visibleCards.last optional

Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift, Pod/Classes/KolodaView/KolodaView.swift, README.md
Some of our end users have been commenting on how taxing it is to swipe cards. Allowing the ability to override the swipe distance might prove useful for some.
=> Expose method for overriding card `actionMargin`

Example/Podfile, Pod/Classes/KolodaView/KolodaView.swift
When returning false in ```kolodaShouldTransparentizeNextCard```, the cards were still animating the transparency.
Also fixed example podfile for user's getting compiler errors for 'pop' library.
=> Returning 'false' in 'kolodaShouldTransparentizeNextCard' is broken.

Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift, Pod/Classes/KolodaView/KolodaView.swift, README.md
I added the ability for a user to configure if dragging is enabled for a given card via a delegate method 
`func koloda(koloda: KolodaView, shouldDragCardAtIndex index: UInt ) -> Bool
`
If you don't implement it or return true, the card will drag normally. If you return false, the card won't move at all. 
I needed this for a personal project where I wanted to allow for user interaction on the card itself, but didn't want it to move until certain conditions were met.
=> Allow user to configure if the card should be draggable

Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift
When I use an `UICollectionView` as a subview of a `DraggableCardView`, `didSelectItemAtIndexPath` delegate method is not called. The reason is that `cancelsTouchesInView` property of `tapGestureRecognizer` of `DraggableCardView` equal to `true`. 
Changed `cancelsTouchesInView` to `false` and everything became working as expected.
=> Disallow canceling touches in subviews

Pod/Classes/KolodaView/KolodaView.swift
When trying to remove all cards from the Koloda view I get a Out Of Bound error. I think the issue is that we don't update the new countOfCards soon enough. So when we try to get the missingCardCount it returns an incorrect number (not zero in this case).
This function is called before we update the countOfCards:
```
private func missingCardsCount() -> Int {
return min(countOfVisibleCards - visibleCards.count, countOfCards - (currentCardIndex + 1))
}
```
So I just moved the statement earlier in the function.
Welcome to all feedbacks
=> Fix index out of range when removing all cards

Pod/Classes/KolodaView/KolodaView.swift
Awesome Lib! thank you for your sharing! :)
On implementing a button swipe cards manually (like nope, thank button),
there is no check swipable by delegate method "shouldSwipeCardAtIndex".
therefore,I can swipe cards by tapping button unintensionally.
so I add force swipe option to method "swipe(direction: SwipeResultDirection)".
default value of force option is "true" in order not to affect the existing specifications.
=> check swipable when swipe manually

Pod/Classes/KolodaView/KolodaView.swift
When Koloda is built with Carthage and added to a project which uses Xcode 8 & Swift 3 there is a linker error about a subclass of `KolodaView` named `CustomKolodaView`. It seems to be about the a lazy variable named `animator`.
`Undefined symbols for architecture x86_64:
"direct field offset for Koloda.KolodaView.(animator.storage in _DF55D12D516409CF60937DD60F8B896 Koloda.KolodaViewAnimator?", referenced from: ...
ld: symbol(s) not found for architecture x86_64`
Making the setter of the lazy variable private resolves the issue. But as the setter can be used by others (just like in the example project with the `BackgroundKolodaAnimator`) I had to make it private and create another public variable that is not `lazy` which helps accessing the original `animator`.
=> Fixed the linker error when using Carthage to build Koloda library with Xcode 8

Pod/Classes/KolodaView/KolodaView.swift
Hi there, when `shouldPassthroughTapsWhenNoVisibleCards` is enabled, then the `KolodaView` captures all taps even outside of its bounds. Added a checking.
=> Passthrough taps should be detected only within view bounds

Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift, Pod/Classes/KolodaView/KolodaView.swift
Closes #205
Dev can choose from a number of speed options:
```swift
enum DragSpeed: TimeInterval {
case slow = 2.0
case moderate = 1.5
case `default` = 0.8
case fast = 0.4
}
```
This allows the developer to customise the duration of the swipe animation:
```swift
extension ViewController: KolodaViewDataSource {
func kolodaSpeedThatCardShouldDrag(_ koloda: KolodaView) -> DragSpeed {
return DragSpeed.moderate
}
}
```
=> Allow management of the swipe animation duration

Pod/Classes/KolodaView/KolodaView.swift
This adds a default implementation of `kolodaSpeedThatCardShouldDrag` so that the datasource isn't compelled to provide one when the default speed is sufficient.
=> Use default drag speed when not specified

Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift
Fix a Swift 4.1 warning by converting usage of the deprecated `flatMap` to `compactMap`
=> Fix Swift 4.1 warning

Pod/Classes/KolodaView/KolodaViewAnimatior.swift
Ensure that the inserted card's initial alpha is used as the final alpha value at the end of the insertion animation.
=> Fix issue #375

Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift
I am very happy, and thanks for merging 'isLoop' property.
I have one more thing I want the contentView in DraggableCardView is more open. Then I can interact with contentView direct.
for example, I am controlling the animation of contentView in some condition.
let cards:[DraggableCardView] = subviews.filter{ $0 as? DraggableCardView != nil } as! [DraggableCardView]
for c in cards {
if let g = c.contentView as? EmptyCardView {
if isVisible { // some condition
g.resumeAnim()
} else {
g.pauseAnim()
}
}
}
=> Changed the accessibility of DraggableCardView's contentView

Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift, Pod/Classes/KolodaView/KolodaView.swift
Sometimes,`layoutDeck()` was called from `KolodaView` `layoutSubviews()` during a `DraggableCardView` pan, causing the current card to flicker.
To prevent this, expose `dragBegin` property, and check the front card is not panning before calling `layoutDeck()`
Addresses #386
=> prevent layoutDeck from being called during panGesture.

Cartfile.resolved, Pod/Classes/KolodaView/KolodaView.swift, README.md
Fixes #442 
Detected that impossible to determine when card was rewound and add 
```func koloda(_ koloda: KolodaView, didRewindTo index: Int)``` 
delegate method in KolodaViewDelegate.
=> Have added `didRewindTo ` delegate method.
