Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift
Pod/Classes/KolodaView/KolodaView.swift

Koloda is very nice! I will use Koloda when make Tinder like UI.
I refactored some code. Please review.

Refactoring some code

---

Koloda.podspec

Updated podspec version after pull request.

Updated podspec version.

---

Koloda.podspec
Pod/Classes/KolodaView/KolodaView.swift

Updated podspec versioning after pull request. Fixed first card opacity issue.

Updated podspec. Fixed first card opacity issue.

---

Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift

Updated failable initializer according to new swift syntax.

Updated failable initializer according to new swift syntax.

---

Koloda.podspec
Pod/Classes/KolodaView/KolodaView.swift

Draw rect issue

---

Pod/Classes/KolodaView/KolodaView.swift

Implemented relayout trigger on device rotation.

Implemented relayout trigger on device rotation.

---

Koloda.podspec
README.md

Fixed readme. Updated podspec

---

Koloda.podspec
Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift
Pod/Classes/KolodaView/KolodaView.swift

Fixed glimpsy animation on fast swiping

Fixed glimpsy animation on fast swiping

---

Pod/Classes/KolodaView/KolodaView.swift

Pull Request for Enhancement #42

Pull Request for Enhancement #42 

---

Koloda.podspec
Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift
Pod/Classes/KolodaView/KolodaView.swift
README.md

Fixed frame initializer publicity.
Implemented access to shown cards.
Implemented dragging delegate method.

Issues fix

---

Koloda.podspec
Pod/Classes/KolodaView/KolodaView.swift
README.md

Fixed background animation transparency

Background alpha issue

---

Pod/Classes/KolodaView/KolodaView.swift

Fixed background cards left margin misalignment

---

Pod/Classes/KolodaView/KolodaView.swift

To be able to react to the event.

Added didResetCard method to KolodaViewDelegate.

---

Pod/Classes/KolodaView/KolodaView.swift

Removed erroneous print statement

---

Pod/Classes/KolodaView/KolodaView.swift
README.md

called on setup, swipe animation finish, revert animation finish
Fixes #77

Add didShowCardAtIndex delegate

---

Pod/Classes/KolodaView/KolodaView.swift

Changed animation canceling order, so it doesn't conflict with alpha animation applying.

Changed animation canceling order

---

Example/Podfile

See: https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#100beta1

remove deprecated 'exclusive => true' DSL on Podfile

---

Pod/Classes/KolodaView/KolodaView.swift

- We wanted to display a message below the lowest card of the stack of cards, therefore we needed to be able to force a click to go through it
- Furthermore we added the ability to add/remove the View to the NotificationCenter
- In addition to that we needed the ability to chance all of the default values to our liking, implemented the missing fields in KolodaView

Add click through functionality for KolodaView

---

Info.plist
Koloda.podspec
Pod/Classes/KolodaView/KolodaView.swift
Pod/Classes/KolodaView/KolodaViewAnimatior.swift
README.md

Updated pull request that targets Yalantis:swift-3 instead of Yalantis:master. 
Issue ref: #209

Swift 3 version that allows for Subclassing and Configuration (updated)

---

Pod/Classes/KolodaView/KolodaView.swift

I need to know that visible card(s) run out of or not.
But, there is no property or function to determine that or other way to (because of `visibleCards` is private property).
So, I add computed property `isRunOutOfCards`.
It is only to get Array of `visibleCards` is empty or not. and  I didn't change accessibility of `visibleCards`.
Please review my PR!

Add parameter to determine that card is empty or not

---

Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift
Pod/Classes/KolodaView/KolodaCardStorage.swift
Pod/Classes/KolodaView/KolodaView.swift

Instead of writing a custom class altogether that overrides default behaviour, this is a middle-ground way of thinking. Provide the default and allow the user to override if necessary. Backward-compatible.

Public animation constants

---

Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift

I'm almost 100% positive that self. was inserted in my previous pull request... Anyway, I fixed it again now.

self. is needed for proper compilation

---

README.md

This PR updates all occurrences of currentCardNumber to currentCardIndex in README.

Update README - rename currentCardNumber to currentCardIndex

---

Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift
Pod/Classes/KolodaView/KolodaView.swift
Pod/Classes/KolodaView/KolodaViewAnimatior.swift

Hi, I've added support to reverse a swipe from a direction (#204). The user would have to keep track of the direction for now. We can improve this PR to keep track of the direction.
```
// Perform direction animation
kolodaView.revertAction(direction: .right)
// Perform fade animation
kolodaView.revertAction()
``` 
You can use fade and direction together as well.
Let me know if you disagree with any of the changes.

Added Revert Animation

---

Pod/Classes/KolodaView/KolodaView.swift

I am using Koloda in project. 
Thanks koloda.
I added looping property. 
I will be glad if this feature is added in koloda.
If Another solution exists, please let me know...

Add isLoop property for looping cards

---

Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift
Pod/Classes/KolodaView/KolodaView.swift

I need to know the start-time and finish-time of dragging for more interacting motion.
I think this delegation is useful for some people..

Added delegate function for pan gesture

---

Example/Koloda.xcodeproj/project.pbxproj
Example/Koloda.xcodeproj/xcshareddata/xcschemes/Koloda-Example.xcscheme
Pod/Classes/KolodaView/KolodaView.swift
README.md

- Updated LatestSwiftMigration to 5.0
- Only code change was index(of:) -> firstIndex(of:)
- Changed developmentRegion code to ISO 639-1 (preferred)
- Automatic change from `${SRCROOT}/Pods` to `${PODS_ROOT}`
--------
- Enhancement
- Low Priority

Update to Swift 5.0

---

Pod/Classes/KolodaView/KolodaView.swift

#434 
Detected crash and fixed.

#434 removed force unwrap

---

Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift
Pod/Classes/KolodaView/KolodaView.swift

This PR is for the issue #470.

[Change] Replace Class-Only Protocol from class to AnyObject

---

Koloda.podspec
Koloda.xcodeproj/project.pbxproj

Updated minimum deployments to 11.0

Updating minimum deployments
